#!/usr/bin/env bash

function show_help() {
    echo "Usage:        $(basename $0) [options]"
    echo "Options:      help        显示帮助"
    echo "              init path   初始化 将度盘中的path文件夹和当前目录关联起来"
    echo "              commit      更新保存在本地的度盘文件列表和本地文件列表"
    echo "              diff        显示度盘和本地目录中的文件差异"
    echo "              push        将本地有但度盘中没有的文件上传到度盘"
    echo "              pull        将本地没有但度盘中有的文件下载到本地"
    echo "              sync        push + pull"
    echo "Examples:     $(basename $0) init /音乐/谭晶 && $(basename $0) diff"
    echo "              $(basename $0) commit && $(basename $0) sync"
}

IFS=$'\n'

case "$1" in
'help') show_help && exit 1 ;;
'init')
    echo "$2" >.path

    # 将度盘上的文件按大小升序排列 依靠“2021-11-20 09:16:15”这样的时间格式筛出所有文件名
    baidupcs ls --size $(cat .path) | sed -n 's/.*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\(.*\)/\1/p' | awk '$1=$1' >.remote

    # 将本地文件按大小升序排列
    ls -Sr >.local
    ;;
'commit')
    baidupcs ls --size $(cat .path) | sed -n 's/.*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\(.*\)/\1/p' | awk '$1=$1' >.remote
    ls -Sr >.local
    ;;
'diff')
    echo '***** 远程有 本地无 *****'
    diff .local .remote | sed -n 's/> \(.*\)/\1/p'

    echo '***** 远程无 本地有 *****'
    diff .local .remote | sed -n 's/< \(.*\)/\1/p'
    ;;
'push')
    for file in $(diff .local .remote | sed -n 's/< \(.*\)/\1/p'); do
        baidupcs upload "$(pwd)/$file" $(cat .path)
    done

    baidupcs ls --size $(cat .path) | sed -n 's/.*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\(.*\)/\1/p' | awk '$1=$1' >.remote
    ;;
'pull')
    for file in $(diff .local .remote | sed -n 's/> \(.*\)/\1/p'); do
        baidupcs download -saveto "$(pwd)/" $(cat .path)/"$file"
    done

    ls -Sr >.local
    ;;
'sync')
    for file in $(diff .local .remote | sed -n 's/< \(.*\)/\1/p'); do
        baidupcs upload "$(pwd)/$file" $(cat .path)
    done
    for file in $(diff .local .remote | sed -n 's/> \(.*\)/\1/p'); do
        baidupcs download -saveto "$(pwd)/" $(cat .path)/"$file"
    done

    baidupcs ls --size $(cat .path) | sed -n 's/.*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\(.*\)/\1/p' | awk '$1=$1' >.remote
    ls -Sr >.local
    ;;
*) echo "Error: unknown commands!" && exit 1 ;;
esac
