#!/usr/bin/env bash

set -euo pipefail

README="${1:-README.md}"

if ! command -v tree >/dev/null 2>&1; then
    echo "Error: tree not found."
    exit 1
fi

if [ ! -f "$README" ]; then
    touch $README
fi

tree -L 3 -I '*.sh|*.md' >$README
sed -i '1c\```text' $README
sed -i '$i\```' $README
sed -i '/^$/d' $README

echo "Updated $README"
