#!/usr/bin/env bash

set -euo pipefail

README="${1:-README.md}"

if ! command -v tree >/dev/null 2>&1; then
    echo "Error: tree not found."
    exit 1
fi

if [ ! -f "$README" ]; then
    touch $README
fi

tree_output=$(tree -L 3 -I '*.sh|*.md' .)

{
    echo '```text'
    echo " $ tree_output"
    echo '```'
} >"$README"

echo "Updated $README"
