#!/usr/bin/env bash
# script $1
# $1: file folder path

if [ -f filelist.txt ]; then
    rm filelist.txt
fi

touch filelist.txt

while IFS= read -d $'\0' -r file; do
    printf '%s\n' "$file" >>filelist.txt
done < <(find $1 -print0)
