#!/usr/bin/env bash

# for modify the path of *.js files
sed -i 's/src="\(.*\)head.min.js"/src="..\/common\/js\/head.min.js"/g' "$1"
sed -i 's/src="\(.*\)reveal.js"/src="..\/common\/js\/reveal.js"/g' "$1"
sed -i 's/src="\(.*\)MathJax.js"/src="..\/common\/js\/mathjax\/MathJax.js"/g' "$1"
sed -i 's/"src":"\(.*\)notes.js"/"src":"..\/common\/js\/notes\/notes.js"/g' "$1"
sed -i 's/src="\(.*\)mermaid.min.js"/src="..\/common\/js\/mermaid\/mermaid.min.js"/g' "$1"

# delete the line which imports none.css
sed -i '/none.css/d' "$1"
